# 安裝 Numpy
若有語法不了解的地方，可以參考以下連結:
- [NumPy Reference](https://numpy.org/doc/stable/reference/index.html)
- [NumPy Tutorial](https://www.w3schools.com/python/numpy/default.asp)
- [NumPy 教程](https://www.runoob.com/numpy/numpy-tutorial.html)

In [ ]:
'''
註:
- 也可以在 conda 的虛擬環境中 (如 da) 裡面安裝 Numpy。
  - 指令: pip install -U numpy。
- 如果直接安裝 pandas，會連同 numpy 一起安裝。
  - 指令: pip install -U pandas
'''

!pip install -U pandas

In [1]:
# 匯入套件
import numpy as np

建議遇到不確定如何使用的語法，可以經常查詢官方的文件
- [doc 版本列表](https://numpy.org/doc/)
- [當前 stable 版本](https://numpy.org/doc/stable/reference/index.html)

# np.array(): 產生陣列 (Array)

In [ ]:
# 語法查詢
np.array?

In [ ]:
# 在未完成的語法後面按下 tab 鍵，會開啟自動完成功能 (語法提示) 
np.ar

In [2]:
'''
numpy.array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0, like=None)
'''
# 0 維陣列
a = np.array(33)
print(a + a)

66


In [3]:
# 一維陣列
a = np.array([0,1,2,3])
'''
註:
np.array() 裡面的 [0,1,2,3]，是 Python 的 List (串列) 變數，
而使用 np.array([0,1,2,3]) 賦值之後的 a，
它是真正的 Array (陣列)
'''

# 在 cell 裡面，程式碼最後一行是變數名稱時，可以自動預覽結果
a

array([0, 1, 2, 3])

In [4]:
# 如果希望宣告變數後，直接預覽變數，可以用「;」隔開，寫在同一行:
a = np.array([0,1,2,3]); a

array([0, 1, 2, 3])

In [5]:
# 二維陣列
'''
長這個樣子:
arr = [
    [0,1,2], 
    [3,4,5]
]
'''
a = np.array([[0,1,2], [3,4,5]]); a

array([[0, 1, 2],
       [3, 4, 5]])

# Numpy 的 shape, ndim, dtype

In [6]:
# shape (形狀，以 tuple 格式呈現)
'''
(2, 3) 代表 2 維陣列:
- 有 2 列，每 1 列有 3 個元素，
- 也可看成幾個 row、幾個 column
'''
a.shape

(2, 3)

In [7]:
# ndim (n-dimensions，維度)
a.ndim

2

In [8]:
# dtype (data-type，陣列當中每一個元素的屬性)
a.dtype

dtype('int32')

In [9]:
# 1 維陣列的 shape 長什麼樣子?
'''
說明:
- (4) 代表一個數字
- (4,) 代表一個 tuple (1 維陣列)
- (1, 4) 代表 2 維陣列，裡面只有 1 維的資料，該維有 4 個元素，例如 np.array([[1,2,3,4]])
'''
a.shape

(2, 3)

# np.arange(): 從數值範圍來建立陣列

In [10]:
# 跟 range() 用法一樣
'''
用法:
numpy.arange([start, ]stop, [step, ]dtype=None, *, like=None)
'''
a = np.arange(10); a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
# 取得陣列 [1, 2, 3, 4, 5, 6, 7, 8, 9]
a = np.arange(1, 10); a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
# 1 ~ 10 之間，每隔 3 個元素，加入資料到陣列: [1, 4, 7]
a = np.arange(1, 10, 3); a

array([1, 4, 7])

# Numpy的資料型態 (data-type)

In [13]:
# 自動判斷資料型態
a = np.array([1,2,3,4]); a.dtype

dtype('int32')

In [14]:
# 自動判斷資料型態 (其中一個元素變成浮點數，dtype 會自動轉型)
a = np.array([1., 2, 3, 4]); a.dtype

dtype('float64')

In [15]:
# 指定陣列每一個資料的資料型態 (指定 float64)
a = np.array([1, 2, 3, 4], dtype='float64')
a
# a.dtype

array([1., 2., 3., 4.])

In [17]:
# 布林值用於 numpy
a = np.array([True, True, False]); a.dtype

dtype('bool')

In [18]:
# 類型轉換 (float 轉成 int)
a = np.array([1, 2, 3.14]) # dtype('float64')
a_ = a.astype(int); a_

array([1, 2, 3])

# Array creation routine 用於創建多維陣列的函數

In [19]:
# np.linspace(): 建立等距陣列的 1 維陣列
'''
np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
'''
a = np.linspace(1, 9, num=3); a

array([1., 5., 9.])

In [20]:
# np.ones(): 建立填滿 1 的陣列，透過 shape 指定幾維
'''
numpy.ones(shape, dtype=None, order='C', *, like=None)[source]
'''
a = np.ones((2,3)); a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
# np.zeros(): 建立填滿 0 的陣列，透過 shape 指定幾維 
'''
numpy.zeros(shape, dtype=float, order='C', *, like=None)
'''
a = np.zeros((5,)); a

array([0., 0., 0., 0., 0.])

In [23]:
# np.full(): 建立填滿 fill_value 的陣列，透過 shape 指定幾維 
'''
numpy.full(shape, fill_value, dtype=None, order='C', *, like=None)
'''
a = np.full((3,4), 10); a

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])