In [1]:
import numpy as np

# 一維陣列的四則運算

In [2]:
# 初始化陣列
x = np.array([2, 4, 6, 8, 10])
y = np.array([10, 8, 6, 4, 2])

In [3]:
# 整數與陣列: 加法
a = x + 4; a

array([ 6,  8, 10, 12, 14])

In [4]:
# 整數與陣列: 減法
a = x - 2; a

array([0, 2, 4, 6, 8])

In [5]:
# 整數與陣列: 乘法
a = x * 2; a

array([ 4,  8, 12, 16, 20])

In [6]:
# 整數與陣列: 除法
a = x / 2; a

array([1., 2., 3., 4., 5.])

In [7]:
# 陣列加法運算
a = x + y; a

array([12, 12, 12, 12, 12])

In [8]:
# 陣列減法運算
a = x - y; a

array([-8, -4,  0,  4,  8])

In [9]:
# 陣列乘法運算
a = x * y; a

array([20, 32, 36, 32, 20])

In [10]:
# 陣列除法運算
a = x / y; a

array([0.2, 0.5, 1. , 2. , 5. ])

In [11]:
# 陣列元素平方
'''
也可以使用
A = np.square(x)
B = np.square(y)
'''
A = x ** 2
B = y ** 2

In [12]:
A

array([  4,  16,  36,  64, 100])

In [13]:
B

array([100,  64,  36,  16,   4])

In [14]:
# 陣列元素開根號
A = np.sqrt(x)
B = np.sqrt(y)

In [15]:
A

array([1.41421356, 2.        , 2.44948974, 2.82842712, 3.16227766])

In [16]:
B

array([3.16227766, 2.82842712, 2.44948974, 2.        , 1.41421356])

# 關係運算子運算

以 大於 (>)、小於 (<)、等於 (==) 為例

In [17]:
# 大於
a = x > y; a

array([False, False, False,  True,  True])

In [18]:
# 小於
a = x < y; a

array([ True,  True, False, False, False])

In [19]:
# 等於
a = x == y; a

array([False, False,  True, False, False])

# 陣列索引與切片 (Indexing & Slicing)

In [20]:
# 指定索引
x[0]

2

In [21]:
# 切片 (範圍: [start, end-1, step])
x[0:2]

array([2, 4])

In [22]:
# 切片，指定每幾步算一次
'''
這樣也可以
x[::2]
'''
x[0:5:2]

array([ 2,  6, 10])

In [23]:
# 切片 (使用負號)
x[-1]

10

In [24]:
# 切片 (範圍: [start, end-1, step])
x[-3:-1]

array([6, 8])

# 陣列的結合與加入

In [25]:
# 陣列結合
'''
numpy.concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")
'''
z = np.concatenate((x, y)); z

array([ 2,  4,  6,  8, 10, 10,  8,  6,  4,  2])

In [26]:
# 將陣列元素加入其它陣列
z = np.concatenate((x, [12, 14, 16])); z

array([ 2,  4,  6,  8, 10, 12, 14, 16])

# 在陣列指定索引插入元素 insert()

原本 x 是 [2,4,6,8,10]

In [27]:
# 在陣列指定索引 2 插入元素 9
'''
numpy.insert(arr, obj, values, axis=None)
'''
z = np.insert(x, 2, 9); z

array([ 2,  4,  9,  6,  8, 10])

In [28]:
# 在陣列指定索引 1 跟 3，分別插入元素 7 跟 9
z = np.insert(x, [1,3], [7,9]); z

array([ 2,  7,  4,  6,  9,  8, 10])

# 刪除指定索引的陣列元素 delete()

In [29]:
# 刪除索引 1 的元素
'''
numpy.delete(arr, obj, axis=None)
'''
z = np.delete(x, 1); z

array([ 2,  6,  8, 10])

In [30]:
# 刪除索引 1 和 3 所放置的元素
z = np.delete(x, [1, 3]); z

array([ 2,  6, 10])

# 向量內部元素總和 sum()

In [31]:
# 計算元素總和
'''
numpy.sum(a, axis=None, dtype=None, ...)
'''
c = np.array([1, 3, 5, 7])
d = np.sum(c); d

16

# 向量內積 (inner product)

In [ ]:
'''
內積在機器學習的領域，是很重要的概念，
無論是取得向量特徵，或是向量間的關係，
內積都扮演重要的角色

numpy.inner(a, b, /)
'''
a = np.array([4,5,1,3,4])
b = np.array([5,3,5,4,2])

'''
計算過程:
4*5 + 5*3 + 1*5 + 3*4 + 4*2 = 60
'''

c = np.inner(a, b); c

# 牛刀小試: 餘弦相似度 (Cosine Similarity)
參考網頁: [https://zh.wikipedia.org/wiki/余弦相似性](https://zh.wikipedia.org/wiki/余弦相似性)
![餘弦相似性](https://wikimedia.org/api/rest_v1/media/math/render/svg/2a8c50526e2cc7aa837477be87eff1ea703f9dec)


假設某 A 的向量為 \[4,5,1,3,4\]，某 B 的向量為 \[5,3,5,4,2\]，餘弦相似度的算法為:
![Cosine Similarity](https://i.imgur.com/NOQBXuN.png)

