In [1]:
import numpy as np

In [2]:
# 建立二維陣列
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

# 二維陣列相對位置與四則運算

In [3]:
# 與整數的加法運算
a = x + 10; a

array([[11, 12],
       [13, 14]])

In [4]:
# 加法運算
a = x + y; a

array([[ 6,  8],
       [10, 12]])

In [5]:
# 相對位置乘法運算
'''
註: 這裡是陣列運算，與矩陣 (matrix) 運算是不一樣的作法
'''
a = x * y; a

array([[ 5, 12],
       [21, 32]])

In [6]:
# 相對位置除法運算
a = x / y; a

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

# 關係運算子運算

In [7]:
# 大於
a = x > y; a

array([[False, False],
       [False, False]])

In [8]:
# 小於
a = x < y; a

array([[ True,  True],
       [ True,  True]])

# 取得與設定二維陣列元素 (Indexing)

In [9]:
# 取得二維陣列某元素內容
x[0, 1] # row = 0, col = 1

2

In [10]:
# 設定二維陣列某元素內容
tmp = np.array([[5, 5, 6, 6], [3, 3, 1, 2]])
tmp[1, 2] = 11; tmp

array([[ 5,  5,  6,  6],
       [ 3,  3, 11,  2]])

In [11]:
# 取得 row = 0 的元素
'''
x[0] 的內容: [[1,2], [3,4]]

以下方式同樣效果
x[0,]
x[0,:]
'''
x[0]

array([1, 2])

In [12]:
# 取得 column = 0 的元素
'''
x[0] 的內容: [[1,2], [3,4]]

以下方式同樣效果
x[:,0]
'''
x[:,0]

array([1, 3])

# 切片 (Slicing)

在這裡使用 xx = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [13]:
xx = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [14]:
# 取得 row = 0 的前 3 個元素
xx[0, :3]

array([1, 2, 3])

In [15]:
# 取得 row=0:2, column=2:4
'''
實際上是 row 0 ~ row 1，以及 column 2 和 column 3 的資料
'''
xx[0:2, 2:4]

array([[3, 4],
       [7, 8]])

In [16]:
# 取得前 2 個 row 的元素
xx[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [17]:
# 取得 row = 1 之後的元素
xx[1:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# 更改陣列形狀 (即是改變陣列維度)

In [18]:
# 建立一維陣列
x1 = np.array([1, 2, 3, 4, 5, 6])

In [19]:
# 轉成 2x3 陣列  (2 列 3 行，2 rows，3 columns)
# 註: 「不會」修改原始陣列，「會」回傳轉換後的新陣列
y1 = x1.reshape(2, 3); y1

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
# 將 2x3 陣列轉成一維陣列
'''
numpy.ravel(a, order='C')
'''
x2 = y1.ravel(); x2

array([1, 2, 3, 4, 5, 6])

In [21]:
# 將 2x3 陣列，改成 3x2 陣列
# 註: 「會」修改原始陣列，「不會」回傳轉換後的新陣列
y1.resize(3,2); y1

array([[1, 2],
       [3, 4],
       [5, 6]])

# 轉置矩陣 transpose()

把 n x m 的矩陣，變成 m x n 的矩陣

In [22]:
# 生成一維陣列 (0 - 7)，reshape 成 4 列 2 行後，再 transpose 成為 2 列 4 行
a = np.arange(8).reshape(4, 2); a
'''
reshape 後的結果:
[[0, 1],
 [2, 3],
 [4, 5],
 [6, 7]]
'''
b = a.transpose(); b

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

In [23]:
# 也可以使用 T 來進行 transpose
a = np.arange(8).reshape(4, 2); a
b = a.T; b

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

# 廣播 (broadcast)

執行 2 個陣列運算時，原則上必須外形相同才能運算，如果不同，可以使用廣播 (broadcasting) 機制，將小陣列「擴大」到兩個陣列都相同，之後再進行運算。

![Computation on Arrays: Broadcasting](https://i.imgur.com/CuB6Bsh.png)
參考資料: [Computation on Arrays: Broadcasting](https://jakevdp.github.io/PythonDataScienceHandbook/02.05-computation-on-arrays-broadcasting.html)

In [29]:
# np.arange(3) + 5 是否等於 [5,6,7] ?
a = np.arange(3) + 5; a

array([5, 6, 7])

In [30]:
# np.ones((3, 3)) + np.arange(3) 是否等於 [[1,2,3],[1,2,3],[1,2,3]] ?
a = np.ones((3, 3)) + np.arange(3); a

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [31]:
# np.arange(3).reshape((3,1)) + np.arange(3) 是否等於 [[0,1,2],[1,2,3],[2,3,4]] ?
a = np.arange(3).reshape((3,1)) + np.arange(3); a

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])