# 「加總」sum()、「乘積」prod()、「差」diff()

In [1]:
import numpy as np

In [2]:
# 一維陣列的「和」 (加總)
np.sum([1, 2, 3, 4])

10

In [3]:
# 二維陣列的「和」 (加總)
np.sum([[1,2], [3,4]])

10

軸 (axis) 的概念
![軸 (axis) 的概念](https://i.imgur.com/u7ItSQZ.png)

參考資料: [Numpy Axes, Explained](https://youtu.be/aF96TC_6kDg)

In [4]:
# 二維陣列的「和」，指定軸 (axis) 來計算
'''
[
    [1,2], 
    [3,4], 
    [5,6]
]

axis = None: 
- 所有元素，不分列 (row) 或行 (column)。預設值。
axis = 0:
- 順著 [0][0], [1][0], [2][0], ... 等索引號碼增加的方向
- 類似座標的 y 軸，針對每一個元素 y 軸對應的位置 (由上而下) 進行計算
axis = 1: 
- 順著 [0][0], [0][1], [0][2], ... 等索引號碼增加的方向
- 類似座標的 x 軸，針對每一個元素 x 軸對應的位置 (由左而右) 進行計算
'''
np.sum([[1,2], [3,4], [5,6]], axis=None)

21

In [5]:
# 一維陣列的「乘積」
np.prod([1, 2, 3, 4])

24

In [6]:
# 二維陣列的「乘積」
np.prod([[1, 2], [3, 4]])

24

In [7]:
# 二維陣列的「乘積」，指定軸 (axis) 來計算
'''
[
    [1,2], 
    [3,4], 
    [5,6]
]

axis = None: 
- 所有元素，不分列 (row) 或行 (column)。預設值。
axis = 0:
- 順著 [0][0], [1][0], [2][0], ... 等索引號碼增加的方向
- 類似座標的 y 軸，針對每一個元素 y 軸對應的位置 (由上而下) 進行計算
axis = 1: 
- 順著 [0][0], [0][1], [0][2], ... 等索引號碼增加的方向
- 類似座標的 x 軸，針對每一個元素 x 軸對應的位置 (由左而右) 進行計算
'''
np.prod([[1,2], [3,4], [5,6]], axis=None)

720

In [8]:
# 一維陣列的「差」(後一個元素的值，減去前一個元素的值)
'''
numpy.diff(a, n=1, axis=-1, prepend=<no value>, append=<no value>)
'''
x = np.array([7, 5, 3, 3, 9, 6, 7])
np.diff(x)

array([-2, -2,  0,  6, -3,  1])

In [9]:
# 一維陣列的「差」(指定 n，代表 diff 幾次)
np.diff(x, n=2)

array([ 0,  2,  6, -9,  4])

In [10]:
# 二維陣列的「差」，指定軸 (axis) 來計算
'''
[
    [1,2], 
    [3,4], 
    [5,6]
]

axis = None: 
- 所有元素，不分列 (row) 或行 (column)。預設值。
axis = 0:
- 順著 [0][0], [1][0], [2][0], ... 等索引號碼增加的方向
- 類似座標的 y 軸，針對每一個元素 y 軸對應的位置 (由上而下) 進行計算
axis = 1: 
- 順著 [0][0], [0][1], [0][2], ... 等索引號碼增加的方向
- 類似座標的 x 軸，針對每一個元素 x 軸對應的位置 (由左而右) 進行計算
'''
x = np.array([[1,2], [3,4], [5,6]])
np.diff(x, axis=0)

array([[2, 2],
       [2, 2]])

# 捨去函數

In [11]:
# around(): 四捨五入到最近的「偶數值」
'''
numpy.around(a, decimals=0, out=None)

decimals: 指定小數位數 (小數點後面第幾位)
'''
np.around([0.45, 1.85], 1)

array([0.4, 1.8])

In [12]:
# rint(): 回傳最近的整數 (四捨五入到最近的「偶數值」)
np.rint([1.5, 2.5, 1.6, 3.3])

array([2., 2., 2., 3.])

In [13]:
# floor(): 無條件捨去
np.floor([1.5, 2.5, 1.6, 3.3])

array([1., 2., 1., 3.])

In [14]:
# ceil(): 無條件進位
np.ceil([1.1, 2.5, 1.6, 3.3])

array([2., 3., 2., 4.])

In [15]:
# trunc(): 捨棄小數
np.trunc([1.1, 2.5, 1.6, 3.3])

array([1., 2., 1., 3.])

# 指數 (exp) 與對數 (log)

In [16]:
# exp(): 自然對數 e 的幾次方
'''
e^1 = 2.71828183
e^2 = 7.3890561
e^3 = 20.08553692
e^4 = 54.59815003
.
.
.
'''
np.exp([1, 2, 3, 4])

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [17]:
# exp2(): 2 的幾次方
np.exp2([1, 2, 3, 4])

array([ 2.,  4.,  8., 16.])

In [18]:
# log(): 計算自然對數的值
'''
np.e = 自然對數

註: 
log(1) = 0 (任何數的 0 次方，等於 1)
log(e) = 1
log(e^2) = 2
'''
np.log([1, np.e, np.e ** 2])

array([0., 1., 2.])

In [19]:
# log2(): 計算以 2 為底的值
np.log2([1, 2, 4, 8])

array([0., 1., 2., 3.])

In [20]:
# log10(): 計算以 10 為底的值
np.log10([1, 10, 100, 1000])

array([0., 1., 2., 3.])

In [21]:
# absolute(): 回傳絕對值
np.absolute([-3, 3])

array([3, 3])

In [22]:
# square(): 回傳平方值
np.square([4, 9])

array([16, 81])

In [23]:
# sqrt(): 回傳平方根
np.sqrt([4, 9])

array([2., 3.])

# 隨機函數
- np.random.rand(dim0\[, dim1, dim2, ...\])
- np.random.randint(low, high=None, size=None)
- 參考資料: 
  - [Random sampling](https://numpy.org/doc/stable/reference/random/index.html)
  - [python numpy 常用随机数的产生方法](https://blog.csdn.net/m0_37804518/article/details/78490709)

In [24]:
'''
np.random.seed(42)
numpy.random.rand(): 設定種子後，取得隨機亂數

註: np.random.seed() 的引數固定，隨機產生的值也會固定，亂數的值介於 [0, 1)
'''
np.random.seed(42)
a = np.random.rand(3); a

array([0.37454012, 0.95071431, 0.73199394])

In [2]:
'''
np.random.randint(start, end, size=數量): 產生 start 到 end - 1 之間的整數值

隨機產生 100 位同學的成績
'''
a = np.random.randint(0, 100, size=100); a

array([53,  9, 65, 56, 44, 42, 17, 23, 55, 14, 21, 25, 78, 34, 56, 35, 55,
       32, 33, 84, 38, 51, 81, 55, 85, 58, 96, 89, 13, 49, 13, 15, 47, 20,
       41, 16, 61, 55, 42, 43, 38, 26, 36, 98, 88, 95, 42, 80, 67, 73,  4,
       31, 91,  9, 84, 99, 52, 76, 18, 30, 72, 27, 50, 56,  6, 93, 28,  4,
        6, 44, 10, 17, 61, 71, 72, 59, 68,  4,  0, 40, 38, 69, 80, 72, 74,
       89, 53, 40, 50, 91, 77, 75, 90, 66, 60, 30,  9, 42, 63, 22])

In [26]:
'''
np.random.shuffle(): 陣列元素重新排列
'''
x = np.arange(10)
np.random.shuffle(x)
x

array([1, 5, 2, 4, 3, 7, 9, 6, 8, 0])

# 其它

In [27]:
# mean(): 元素平均值
x = np.array([[1, 2], [3, 4]])
np.mean(x)

2.5

In [28]:
# mean() 加上 axis
np.mean(x, axis = 0)

array([2., 3.])

In [29]:
# median(): 中位數
x = np.array([[12, 7, 4], [3, 2, 6]])
np.median(x)

5.0

In [30]:
# median() 加上 axis
np.median(x, axis = 0)

array([7.5, 4.5, 5. ])